/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;
import lcd.ArduinoLCD;
import teclado.ArduinoTeclado;

/**
 *
 * @author Rangel
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        actualizarPuertos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelTestLCD = new javax.swing.JPanel();
        eti1 = new javax.swing.JLabel();
        panelToolsTestLCD = new javax.swing.JPanel();
        txtMensajeTextLCD = new javax.swing.JTextField();
        btnEnviarTestLCD = new javax.swing.JButton();
        panelPuertos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelToolsPuertos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPuertoLCD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPuertoTeclado = new javax.swing.JTextField();
        btnactualizarPuertos = new javax.swing.JButton();
        panelServo = new javax.swing.JPanel();
        spinnerServo = new javax.swing.JSpinner();
        btnMover = new javax.swing.JButton();
        btnLumenes = new javax.swing.JButton();
        btnLeerColor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setLayout(new java.awt.GridLayout(6, 1));

        panelTestLCD.setLayout(new java.awt.GridLayout(2, 0));

        eti1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eti1.setText("TEST LCD");
        panelTestLCD.add(eti1);

        panelToolsTestLCD.setLayout(new java.awt.GridLayout(1, 2));
        panelToolsTestLCD.add(txtMensajeTextLCD);

        btnEnviarTestLCD.setText("Enviar");
        btnEnviarTestLCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarTestLCDActionPerformed(evt);
            }
        });
        panelToolsTestLCD.add(btnEnviarTestLCD);

        panelTestLCD.add(panelToolsTestLCD);

        panelFondo.add(panelTestLCD);

        panelPuertos.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setText("Puertos utilizados");
        panelPuertos.add(jLabel1);

        panelToolsPuertos.setLayout(new java.awt.GridLayout(1, 5));

        jLabel2.setText("LCD");
        panelToolsPuertos.add(jLabel2);

        txtPuertoLCD.setText("COM8");
        panelToolsPuertos.add(txtPuertoLCD);

        jLabel3.setText("Teclado");
        panelToolsPuertos.add(jLabel3);

        txtPuertoTeclado.setText("COM3");
        panelToolsPuertos.add(txtPuertoTeclado);

        btnactualizarPuertos.setText("Actualizar");
        btnactualizarPuertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarPuertosActionPerformed(evt);
            }
        });
        panelToolsPuertos.add(btnactualizarPuertos);

        panelPuertos.add(panelToolsPuertos);

        panelFondo.add(panelPuertos);

        panelServo.setLayout(new java.awt.GridLayout(1, 2));
        panelServo.add(spinnerServo);

        btnMover.setText("Mover Servo (Porcentaje)");
        btnMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoverActionPerformed(evt);
            }
        });
        panelServo.add(btnMover);

        panelFondo.add(panelServo);

        btnLumenes.setText("Leer Lumenes");
        btnLumenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLumenesActionPerformed(evt);
            }
        });
        panelFondo.add(btnLumenes);

        btnLeerColor.setText("Leer color");
        btnLeerColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerColorActionPerformed(evt);
            }
        });
        panelFondo.add(btnLeerColor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarTestLCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarTestLCDActionPerformed
        System.out.print("Envieando: " + txtMensajeTextLCD.getText());
        System.out.println(" Num Char: " + txtMensajeTextLCD.getText().length());
        Thread hilo = new Thread(new Runnable() {
            @Override
            public void run() {
                conexionLCD.mandarCadena(txtMensajeTextLCD.getText());
            }
        });
        hilo.start();
    }//GEN-LAST:event_btnEnviarTestLCDActionPerformed

    private void btnactualizarPuertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarPuertosActionPerformed
        actualizarPuertos();
    }//GEN-LAST:event_btnactualizarPuertosActionPerformed

    private void btnMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoverActionPerformed
        // TODO add your handling code here:
        int pos = (int) spinnerServo.getValue();
        servo(pos);
    }//GEN-LAST:event_btnMoverActionPerformed

    private void btnLeerColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerColorActionPerformed
        toogleColores();
    }//GEN-LAST:event_btnLeerColorActionPerformed

    private void btnLumenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLumenesActionPerformed
        lumenes();
    }//GEN-LAST:event_btnLumenesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    private void servo(int grados) {
        // cONVIERTE EL PORCNTJE EN GRADOS
        //VALIDA
        if (grados > 100 || grados < 0) {
            JOptionPane.showMessageDialog(this, "Si sabias que el porcentaje es de 0 a 100 verdad?");
        } else {
            // Convierte procentaje
            grados = (grados*170)/100;
            String info = SERVO_C+grados;
            System.out.println("Gira mot serv "+grados);
            Thread hilo = new Thread(new Runnable() {
                @Override
                public void run() {
                    conexionLCD.mandarCadena(info);
                }
            });
            hilo.start();
        }
    }

    private void toogleColores() {
        String info = "-" + "ANNA";
        Thread hilo = new Thread(new Runnable() {
            @Override
            public void run() {
                conexionLCD.mandarCadena(info);
            }
        });
        hilo.start();
    }

    private void lumenes() {
        String info = "\\" + "LL";
        Thread hilo = new Thread(new Runnable() {
            @Override
            public void run() {
                conexionLCD.mandarCadena(info);
            }
        });
        hilo.start();
    }

    private void actualizarPuertos() {
        conexionLCD = new ArduinoLCD(txtPuertoLCD.getText());
        conexionTeclado = new ArduinoTeclado(txtPuertoTeclado.getText());
        conexionTeclado.setLCD(conexionLCD);
    }

    private final static String SERVO_C = "~";

    private ArduinoLCD conexionLCD;
    private ArduinoTeclado conexionTeclado;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarTestLCD;
    private javax.swing.JButton btnLeerColor;
    private javax.swing.JButton btnLumenes;
    private javax.swing.JButton btnMover;
    private javax.swing.JButton btnactualizarPuertos;
    private javax.swing.JLabel eti1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelPuertos;
    private javax.swing.JPanel panelServo;
    private javax.swing.JPanel panelTestLCD;
    private javax.swing.JPanel panelToolsPuertos;
    private javax.swing.JPanel panelToolsTestLCD;
    private javax.swing.JSpinner spinnerServo;
    private javax.swing.JTextField txtMensajeTextLCD;
    private javax.swing.JTextField txtPuertoLCD;
    private javax.swing.JTextField txtPuertoTeclado;
    // End of variables declaration//GEN-END:variables
}
